import { UIPalette, UITokens } from '../types';

export interface Theme {
  id: string;
  name: string;
  description: string;
  uiPalette: UIPalette;
  uiTokens: UITokens;
}

export const DEFAULT_THEMES: Theme[] = [
  // 1. 봄날
  {
    id: 'spring',
    name: '봄날',
    description: '따뜻한 봄의 파스텔 톤',
    uiPalette: {
      strokeColor: '#5d4037',
      appBackground: '#fff8f3',
      notePaperBackground: '#fffbf5',
      noteOuterBorderColor: '#d7a5a5',
      noteCenterFoldLineColor: '#ffc4d0',
      widgetBorderColor: '#c48b9f',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#fff5f7',
      profileHeaderBarBg: '#ffc4d0',
      goalsHeaderBarBg: '#ffd6e5',
      ddayHeaderBarBg: '#ffe5ec',
      ohaasaHeaderBarBg: '#e8f5e9',
      bucketHeaderBarBg: '#c8e6c9',
      calendarDateHeaderBg: '#ffc4d000',
      calendarWeekdayHeaderBg: '#ffb3c1',
      calendarGridLineColor: '#ffd6e5',
      calendarCellBackground: '#fffbf8',
      calendarTodayHighlightBg: '#ffe5f0',
      monthTabBg: '#ffc4d033',
      monthTabBgActive: '#ffc4d0',
      monthTabBorderColor: '#c48b9f',
      monthTabTextColor: '#6d4c41',
      keyringMetalColor: '#d4a5a5',
      keyringFrameBorderColor: '#ffc4d000',
      cdWidgetBackground: '#fff8f3',
      cdDiscColor: '#f8bbd0',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#ffe5f0',
      cdDotColor: '#c48b9f',
      textColorPrimary: '#5d4037',
    },
    uiTokens: {
      '--ui-primary-bg': '#f48fb1',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#ec407a',
      '--ui-danger-bg': '#ef5350',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#e53935',
      '--ui-success-bg': '#66bb6a',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#43a047',
      '--ui-sunday-text': '#ef5350',
    },
  },

  // 2. 여름바다
  {
    id: 'summer',
    name: '여름바다',
    description: '시원한 바다의 블루 톤',
    uiPalette: {
      strokeColor: '#01579b',
      appBackground: '#e1f5fe',
      notePaperBackground: '#f1f8ff',
      noteOuterBorderColor: '#4fc3f7',
      noteCenterFoldLineColor: '#81d4fa',
      widgetBorderColor: '#0288d1',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#e0f7fa',
      profileHeaderBarBg: '#81d4fa',
      goalsHeaderBarBg: '#b3e5fc',
      ddayHeaderBarBg: '#4dd0e1',
      ohaasaHeaderBarBg: '#80deea',
      bucketHeaderBarBg: '#a7ffeb',
      calendarDateHeaderBg: '#81d4fa00',
      calendarWeekdayHeaderBg: '#4fc3f7',
      calendarGridLineColor: '#b3e5fc',
      calendarCellBackground: '#f1fdff',
      calendarTodayHighlightBg: '#e0f7fa',
      monthTabBg: '#81d4fa33',
      monthTabBgActive: '#81d4fa',
      monthTabBorderColor: '#0288d1',
      monthTabTextColor: '#01579b',
      keyringMetalColor: '#0277bd',
      keyringFrameBorderColor: '#81d4fa00',
      cdWidgetBackground: '#e1f5fe',
      cdDiscColor: '#29b6f6',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#b3e5fc',
      cdDotColor: '#0277bd',
      textColorPrimary: '#01579b',
    },
    uiTokens: {
      '--ui-primary-bg': '#29b6f6',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#039be5',
      '--ui-danger-bg': '#ff7043',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#f4511e',
      '--ui-success-bg': '#26a69a',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#00897b',
      '--ui-sunday-text': '#ff7043',
    },
  },

  // 3. 가을단풍
  {
    id: 'autumn',
    name: '가을단풍',
    description: '따뜻한 가을의 오렌지 톤',
    uiPalette: {
      strokeColor: '#4e342e',
      appBackground: '#fff3e0',
      notePaperBackground: '#fffaf0',
      noteOuterBorderColor: '#d84315',
      noteCenterFoldLineColor: '#ffab91',
      widgetBorderColor: '#bf360c',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#fff8e1',
      profileHeaderBarBg: '#ffcc80',
      goalsHeaderBarBg: '#ffab91',
      ddayHeaderBarBg: '#ff8a65',
      ohaasaHeaderBarBg: '#bcaaa4',
      bucketHeaderBarBg: '#ffccbc',
      calendarDateHeaderBg: '#ffcc8000',
      calendarWeekdayHeaderBg: '#ffab91',
      calendarGridLineColor: '#ffe0b2',
      calendarCellBackground: '#fffbf5',
      calendarTodayHighlightBg: '#fff3e0',
      monthTabBg: '#ffab9133',
      monthTabBgActive: '#ffab91',
      monthTabBorderColor: '#bf360c',
      monthTabTextColor: '#4e342e',
      keyringMetalColor: '#8d6e63',
      keyringFrameBorderColor: '#ffab9100',
      cdWidgetBackground: '#fff3e0',
      cdDiscColor: '#ff7043',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#ffe0b2',
      cdDotColor: '#bf360c',
      textColorPrimary: '#4e342e',
    },
    uiTokens: {
      '--ui-primary-bg': '#ff7043',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#f4511e',
      '--ui-danger-bg': '#d84315',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#bf360c',
      '--ui-success-bg': '#8d6e63',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#6d4c41',
      '--ui-sunday-text': '#d84315',
    },
  },

  // 4. 겨울눈
  {
    id: 'winter',
    name: '겨울눈',
    description: '깨끗한 겨울의 화이트 톤',
    uiPalette: {
      strokeColor: '#37474f',
      appBackground: '#eceff1',
      notePaperBackground: '#fafafa',
      noteOuterBorderColor: '#90a4ae',
      noteCenterFoldLineColor: '#cfd8dc',
      widgetBorderColor: '#546e7a',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#f5f5f5',
      profileHeaderBarBg: '#b0bec5',
      goalsHeaderBarBg: '#cfd8dc',
      ddayHeaderBarBg: '#e0f2f1',
      ohaasaHeaderBarBg: '#e1f5fe',
      bucketHeaderBarBg: '#e8eaf6',
      calendarDateHeaderBg: '#b0bec500',
      calendarWeekdayHeaderBg: '#90a4ae',
      calendarGridLineColor: '#cfd8dc',
      calendarCellBackground: '#fafafa',
      calendarTodayHighlightBg: '#e0f7fa',
      monthTabBg: '#cfd8dc33',
      monthTabBgActive: '#b0bec5',
      monthTabBorderColor: '#546e7a',
      monthTabTextColor: '#37474f',
      keyringMetalColor: '#78909c',
      keyringFrameBorderColor: '#b0bec500',
      cdWidgetBackground: '#eceff1',
      cdDiscColor: '#90a4ae',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#cfd8dc',
      cdDotColor: '#546e7a',
      textColorPrimary: '#37474f',
    },
    uiTokens: {
      '--ui-primary-bg': '#78909c',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#546e7a',
      '--ui-danger-bg': '#ef5350',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#e53935',
      '--ui-success-bg': '#66bb6a',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#43a047',
      '--ui-sunday-text': '#ef5350',
    },
  },

  // 5. 흑백
  {
    id: 'blackwhite',
    name: '흑백',
    description: '모던한 흑백 톤',
    uiPalette: {
      strokeColor: '#212121',
      appBackground: '#fafafa',
      notePaperBackground: '#ffffff',
      noteOuterBorderColor: '#424242',
      noteCenterFoldLineColor: '#e0e0e0',
      widgetBorderColor: '#212121',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#f5f5f5',
      profileHeaderBarBg: '#e0e0e0',
      goalsHeaderBarBg: '#eeeeee',
      ddayHeaderBarBg: '#bdbdbd',
      ohaasaHeaderBarBg: '#d6d6d6',
      bucketHeaderBarBg: '#e8e8e8',
      calendarDateHeaderBg: '#e0e0e000',
      calendarWeekdayHeaderBg: '#9e9e9e',
      calendarGridLineColor: '#e0e0e0',
      calendarCellBackground: '#ffffff',
      calendarTodayHighlightBg: '#f5f5f5',
      monthTabBg: '#e0e0e033',
      monthTabBgActive: '#bdbdbd',
      monthTabBorderColor: '#424242',
      monthTabTextColor: '#212121',
      keyringMetalColor: '#616161',
      keyringFrameBorderColor: '#e0e0e000',
      cdWidgetBackground: '#fafafa',
      cdDiscColor: '#757575',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#eeeeee',
      cdDotColor: '#424242',
      textColorPrimary: '#212121',
    },
    uiTokens: {
      '--ui-primary-bg': '#424242',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#212121',
      '--ui-danger-bg': '#616161',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#424242',
      '--ui-success-bg': '#757575',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#616161',
      '--ui-sunday-text': '#616161',
    },
  },

  // 6. 딸기케이크
  {
    id: 'dessert-strawberry',
    name: '딸기케이크',
    description: '달콤한 딸기 크림 톤',
    uiPalette: {
      strokeColor: '#880e4f',
      appBackground: '#fce4ec',
      notePaperBackground: '#fff0f5',
      noteOuterBorderColor: '#e91e63',
      noteCenterFoldLineColor: '#f8bbd0',
      widgetBorderColor: '#c2185b',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#fff5f8',
      profileHeaderBarBg: '#f8bbd0',
      goalsHeaderBarBg: '#ffc1e3',
      ddayHeaderBarBg: '#ffcdd2',
      ohaasaHeaderBarBg: '#ffe0ec',
      bucketHeaderBarBg: '#f8bbd0',
      calendarDateHeaderBg: '#f8bbd000',
      calendarWeekdayHeaderBg: '#f48fb1',
      calendarGridLineColor: '#f8bbd0',
      calendarCellBackground: '#fffafc',
      calendarTodayHighlightBg: '#fce4ec',
      monthTabBg: '#f8bbd033',
      monthTabBgActive: '#f8bbd0',
      monthTabBorderColor: '#c2185b',
      monthTabTextColor: '#880e4f',
      keyringMetalColor: '#ad1457',
      keyringFrameBorderColor: '#f8bbd000',
      cdWidgetBackground: '#fce4ec',
      cdDiscColor: '#ec407a',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#f8bbd0',
      cdDotColor: '#c2185b',
      textColorPrimary: '#880e4f',
    },
    uiTokens: {
      '--ui-primary-bg': '#ec407a',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#d81b60',
      '--ui-danger-bg': '#e91e63',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#c2185b',
      '--ui-success-bg': '#f48fb1',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#ec407a',
      '--ui-sunday-text': '#e91e63',
    },
  },

  // 7. 초콜릿
  {
    id: 'dessert-chocolate',
    name: '초콜릿',
    description: '진한 초콜릿 브라운 톤',
    uiPalette: {
      strokeColor: '#3e2723',
      appBackground: '#efebe9',
      notePaperBackground: '#faf8f6',
      noteOuterBorderColor: '#5d4037',
      noteCenterFoldLineColor: '#d7ccc8',
      widgetBorderColor: '#4e342e',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#f5f5dc',
      profileHeaderBarBg: '#bcaaa4',
      goalsHeaderBarBg: '#d7ccc8',
      ddayHeaderBarBg: '#ffe0b2',
      ohaasaHeaderBarBg: '#a1887f',
      bucketHeaderBarBg: '#e0e0e0',
      calendarDateHeaderBg: '#bcaaa400',
      calendarWeekdayHeaderBg: '#a1887f',
      calendarGridLineColor: '#d7ccc8',
      calendarCellBackground: '#faf8f6',
      calendarTodayHighlightBg: '#efebe9',
      monthTabBg: '#d7ccc833',
      monthTabBgActive: '#bcaaa4',
      monthTabBorderColor: '#4e342e',
      monthTabTextColor: '#3e2723',
      keyringMetalColor: '#6d4c41',
      keyringFrameBorderColor: '#bcaaa400',
      cdWidgetBackground: '#efebe9',
      cdDiscColor: '#8d6e63',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#d7ccc8',
      cdDotColor: '#5d4037',
      textColorPrimary: '#3e2723',
    },
    uiTokens: {
      '--ui-primary-bg': '#8d6e63',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#6d4c41',
      '--ui-danger-bg': '#d84315',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#bf360c',
      '--ui-success-bg': '#689f38',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#558b2f',
      '--ui-sunday-text': '#d84315',
    },
  },

  // 8. 푸딩
  {
    id: 'dessert-pudding',
    name: '푸딩',
    description: '부드러운 옐로우 톤',
    uiPalette: {
      strokeColor: '#f57f17',
      appBackground: '#fffde7',
      notePaperBackground: '#fffff0',
      noteOuterBorderColor: '#fbc02d',
      noteCenterFoldLineColor: '#fff9c4',
      widgetBorderColor: '#f9a825',
      widgetSurfaceBackground: '#ffffff',
      widgetInputBackground: '#fffef7',
      profileHeaderBarBg: '#fff9c4',
      goalsHeaderBarBg: '#fff59d',
      ddayHeaderBarBg: '#ffecb3',
      ohaasaHeaderBarBg: '#ffe082',
      bucketHeaderBarBg: '#fff59d',
      calendarDateHeaderBg: '#fff9c400',
      calendarWeekdayHeaderBg: '#ffeb3b',
      calendarGridLineColor: '#fff9c4',
      calendarCellBackground: '#fffef8',
      calendarTodayHighlightBg: '#fffde7',
      monthTabBg: '#fff9c433',
      monthTabBgActive: '#fff9c4',
      monthTabBorderColor: '#f9a825',
      monthTabTextColor: '#f57f17',
      keyringMetalColor: '#fbc02d',
      keyringFrameBorderColor: '#fff9c400',
      cdWidgetBackground: '#fffde7',
      cdDiscColor: '#ffeb3b',
      cdScreenBg: '#ffffff',
      cdButtonBg: '#fff9c4',
      cdDotColor: '#f9a825',
      textColorPrimary: '#f57f17',
    },
    uiTokens: {
      '--ui-primary-bg': '#ffeb3b',
      '--ui-primary-text': '#000000',
      '--ui-primary-hover': '#fdd835',
      '--ui-danger-bg': '#ff6f00',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#e65100',
      '--ui-success-bg': '#9ccc65',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#7cb342',
      '--ui-sunday-text': '#ff6f00',
    },
  },

  // 9. 빈티지
  {
    id: 'vintage',
    name: '빈티지',
    description: '따뜻한 세피아 톤',
    uiPalette: {
      strokeColor: '#3e2723',
      appBackground: '#f4ece4',
      notePaperBackground: '#faf6f0',
      noteOuterBorderColor: '#795548',
      noteCenterFoldLineColor: '#d7ccc8',
      widgetBorderColor: '#5d4037',
      widgetSurfaceBackground: '#fff8f0',
      widgetInputBackground: '#f5f0e8',
      profileHeaderBarBg: '#c5b8a5',
      goalsHeaderBarBg: '#d1c4b0',
      ddayHeaderBarBg: '#c8b89f',
      ohaasaHeaderBarBg: '#bcaaa4',
      bucketHeaderBarBg: '#d7c9ba',
      calendarDateHeaderBg: '#c5b8a500',
      calendarWeekdayHeaderBg: '#a1887f',
      calendarGridLineColor: '#d7ccc8',
      calendarCellBackground: '#faf6f0',
      calendarTodayHighlightBg: '#f0e6d8',
      monthTabBg: '#d7ccc833',
      monthTabBgActive: '#c5b8a5',
      monthTabBorderColor: '#5d4037',
      monthTabTextColor: '#3e2723',
      keyringMetalColor: '#6d5845',
      keyringFrameBorderColor: '#c5b8a500',
      cdWidgetBackground: '#f4ece4',
      cdDiscColor: '#8d6e63',
      cdScreenBg: '#fff8f0',
      cdButtonBg: '#d7ccc8',
      cdDotColor: '#5d4037',
      textColorPrimary: '#3e2723',
    },
    uiTokens: {
      '--ui-primary-bg': '#8d6e63',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#6d4c41',
      '--ui-danger-bg': '#a1665f',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#8a5248',
      '--ui-success-bg': '#81815c',
      '--ui-success-text': '#ffffff',
      '--ui-success-hover': '#6d6d4a',
      '--ui-sunday-text': '#a1665f',
    },
  },

  // 10. 네온
  {
    id: 'neon',
    name: '네온',
    description: '화려한 형광 톤',
    uiPalette: {
      strokeColor: '#1a1a2e',
      appBackground: '#0f0f1e',
      notePaperBackground: '#16213e',
      noteOuterBorderColor: '#00ffff',
      noteCenterFoldLineColor: '#7000ff33',
      widgetBorderColor: '#ff00ff',
      widgetSurfaceBackground: '#1a1a2e',
      widgetInputBackground: '#16213e',
      profileHeaderBarBg: '#ff00ff55',
      goalsHeaderBarBg: '#00ffff55',
      ddayHeaderBarBg: '#ffff0055',
      ohaasaHeaderBarBg: '#00ff0055',
      bucketHeaderBarBg: '#ff006655',
      calendarDateHeaderBg: '#00000000',
      calendarWeekdayHeaderBg: '#7000ff',
      calendarGridLineColor: '#ffffff22',
      calendarCellBackground: '#16213e',
      calendarTodayHighlightBg: '#7000ff33',
      monthTabBg: '#ffffff11',
      monthTabBgActive: '#7000ff',
      monthTabBorderColor: '#00ffff',
      monthTabTextColor: '#00ffff',
      keyringMetalColor: '#ff00ff',
      keyringFrameBorderColor: '#00ffff00',
      cdWidgetBackground: '#0f0f1e',
      cdDiscColor: '#ff00ff',
      cdScreenBg: '#1a1a2e',
      cdButtonBg: '#7000ff',
      cdDotColor: '#00ffff',
      textColorPrimary: '#ffffff',
    },
    uiTokens: {
      '--ui-primary-bg': '#7000ff',
      '--ui-primary-text': '#ffffff',
      '--ui-primary-hover': '#5500cc',
      '--ui-danger-bg': '#ff0066',
      '--ui-danger-text': '#ffffff',
      '--ui-danger-hover': '#cc0052',
      '--ui-success-bg': '#00ff88',
      '--ui-success-text': '#000000',
      '--ui-success-hover': '#00cc6a',
      '--ui-sunday-text': '#ff0066',
    },
  },
];
