import { UIPalette, UITokens } from '../types';

export interface Theme {
  id: string;
  name: string;
  description: string;
  palette: UIPalette;
  uiTokens?: Partial<UITokens>;
}

export const DEFAULT_THEMES: Theme[] = [
  {
    id: 'spring',
    name: '봄날',
    description: '따뜻한 봄의 파스텔 톤',
    palette: {
      primary: '#FFB6C1',
      secondary: '#98D8C8',
      accent: '#F7DC6F',
      background: '#FFF8F0',
      surface: '#FFFFFF',
      text: '#5D4E37',
      textSecondary: '#8B7355',
      border: '#E8D5C4',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'summer',
    name: '여름바다',
    description: '시원한 바다의 블루 톤',
    palette: {
      primary: '#4FC3F7',
      secondary: '#81D4FA',
      accent: '#FFD54F',
      background: '#E3F2FD',
      surface: '#FFFFFF',
      text: '#1565C0',
      textSecondary: '#42A5F5',
      border: '#90CAF9',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'autumn',
    name: '가을단풍',
    description: '따뜻한 가을의 오렌지 톤',
    palette: {
      primary: '#FF8A65',
      secondary: '#FFAB91',
      accent: '#FFD54F',
      background: '#FFF3E0',
      surface: '#FFFFFF',
      text: '#BF360C',
      textSecondary: '#D84315',
      border: '#FFCCBC',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'winter',
    name: '겨울눈',
    description: '깨끗한 겨울의 화이트 톤',
    palette: {
      primary: '#B0BEC5',
      secondary: '#CFD8DC',
      accent: '#90CAF9',
      background: '#ECEFF1',
      surface: '#FFFFFF',
      text: '#37474F',
      textSecondary: '#546E7A',
      border: '#B0BEC5',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'blackwhite',
    name: '흑백',
    description: '모던한 흑백 톤',
    palette: {
      primary: '#424242',
      secondary: '#757575',
      accent: '#BDBDBD',
      background: '#FAFAFA',
      surface: '#FFFFFF',
      text: '#212121',
      textSecondary: '#616161',
      border: '#E0E0E0',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'dessert-strawberry',
    name: '딸기케이크',
    description: '달콤한 딸기 크림 톤',
    palette: {
      primary: '#FF6B9D',
      secondary: '#FFB3D9',
      accent: '#FFC0CB',
      background: '#FFF0F5',
      surface: '#FFFFFF',
      text: '#8B4789',
      textSecondary: '#C71585',
      border: '#FFB6C1',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'dessert-chocolate',
    name: '초콜릿',
    description: '진한 초콜릿 브라운 톤',
    palette: {
      primary: '#8B4513',
      secondary: '#A0522D',
      accent: '#D2691E',
      background: '#F5DEB3',
      surface: '#FAEBD7',
      text: '#3E2723',
      textSecondary: '#5D4037',
      border: '#D7CCC8',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'dessert-mint',
    name: '민트초코',
    description: '상큼한 민트와 초콜릿',
    palette: {
      primary: '#98D8C8',
      secondary: '#7FCDBB',
      accent: '#41B6C4',
      background: '#F0FFF4',
      surface: '#FFFFFF',
      text: '#2C3E50',
      textSecondary: '#34495E',
      border: '#A8DADC',
      error: '#FF6B6B',
      success: '#51CF66',
    },
  },
  {
    id: 'vintage',
    name: '빈티지',
    description: '따뜻한 세피아 톤',
    palette: {
      primary: '#C19A6B',
      secondary: '#D2B48C',
      accent: '#DEB887',
      background: '#F5F5DC',
      surface: '#FFF8DC',
      text: '#704214',
      textSecondary: '#8B4513',
      border: '#D2B48C',
      error: '#CD5C5C',
      success: '#6B8E23',
    },
  },
  {
    id: 'neon',
    name: '네온',
    description: '화려한 형광 톤',
    palette: {
      primary: '#FF10F0',
      secondary: '#00F0FF',
      accent: '#FFFF00',
      background: '#1A1A2E',
      surface: '#16213E',
      text: '#FFFFFF',
      textSecondary: '#E0E0E0',
      border: '#0F3460',
      error: '#FF6B6B',
      success: '#39FF14',
    },
  },
];

